= Kubernetes for Java Developers

== Create Kubernetes Cluster

https://github.com/arun-gupta/kubernetes-java-sample/blob/master/workshop.adoc#create-kubernetes-cluster

== Create Resources

=== Pod

==== Using CLI

. Create pod: `kubectl run wildfly --image=jboss/wildfly --port=8080`
. Check status: `kubectl get -w pods`
.. Show the pod name derived from the Deployment name
. Describe pod: `kubectl describe pod <pod-name>` or `kubectl describe pod/<pod-name>`
. Get logs: `kubectl logs <pod-name>`
.. Use `-f` to tail logs
. Get deployments: `kubectl get deployments`
. Delete deployments: `kubectl delete deployments/wildfly`
. Get deployments: `kubectl get deployments`
. Get pods: `kubectl get pods`

==== Using Configuration File

. Create pod: `kubectl create -f wildfly-pod.yaml`
. Get pods: `kubectl get pods`
.. Wide: `kubectl get pods -o wide`
.. YAML: `kubectl get pods -o yaml`
.. JSON: `kubectl get pods -o json`
. Describe pod: `kubectl describe pod/wildfly-pod`
. Delete pod: `kubectl delete pod/wildfly-pod`
. Get pods: `kubectl get pods`

=== Replication Controller

. Create RC: `kubectl create -f wildfly-rc.yaml`
. Get RC: `kubectl get rc`
. Get pods: `kubectl get pods`
.. Show pod names
.. Show image id downloaded on the second host
. Get pods created by RC: `kubectl describe pods wildfly-rc`
. Get pods with a specified label: `kubectl get pods -l name=wildfly`
. Delete RC: `kubectl delete rc wildfly-rc`

=== Service

. Create Service: `kubectl create -f wildfly-service.yaml`
. Get RC, Service and Pods: `kubectl get rc,service,pods`
. Describe service: `kubectl describe service wildfly-service`
. If Kubernetes is on cloud with LB
.. Get the value of `LoadBalancer Ingress`, access the WildFly landing page at `<IP>:8080`
. Delete multiple resources: `kubectl delete rc/wildfly-rc service/wildfly-service`

=== Load Balancing

. *ClusterIP*: This is default, exposes service on cluster-internal IP.
.. Create service: `kubectl create -f lb-clusterip.yml`
.. Get service: `kubectl get svc`
+
```
NAME              CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
kubernetes        100.64.0.1    <none>        443/TCP    48m
wildfly-service   100.71.85.1   <none>        8080/TCP   13m
```
+
.. Describe service: `kubectl describe svc wildfly-service`
+
```
kubectl describe svc wildfly-service
Name:			wildfly-service
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		app=wildfly-rc-pod
Type:			ClusterIP
IP:			100.71.85.1
Port:			web	8080/TCP
Endpoints:		100.96.1.4:8080,100.96.2.3:8080
Session Affinity:	None
Events:			<none>
```
+
.. Delete service: `kubectl delete -f lb-clusterip.yml`
+
. *NodePort*: Expose service on each node of the cluster at a static port. Service is accessible using `<NodeIP>:<NodePort>`.
.. Create service: `kubectl create -f lb-nodeport.yml`
.. Get service: `kubectl get svc`
+
```
NAME              CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes        100.64.0.1      <none>        443/TCP          1h
wildfly-service   100.67.218.58   <nodes>       8080:30001/TCP   16s
```
+
.. Describe service: `kubectl describe svc wildfly-service`
+
```
Name:			wildfly-service
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		app=wildfly-rc-pod
Type:			NodePort
IP:			100.67.218.58
Port:			web	8080/TCP
NodePort:		web	30001/TCP
Endpoints:		100.96.1.7:8080,100.96.2.6:8080
Session Affinity:	None
Events:			<none>
```
. *LoadBalancer*: Expose the service using a cloud provider's load balancer.
. *ExternalName*: Maps the service to the contents of the external name., buy returning a `CNAME` record with its value.

== Using Maven (Service + Replication Controller + Client Pod)

All the code is in `maven` directory:

. Create Couchbase service: `kubectl create -f couchbase-service.yml`
. Check status: `kubectl get -w pods`
. Run application: `kubectl create -f bootiful-couchbase.yml`
. Check status: `kubectl get -w pods`
.. Show `ContainerCreating`
. Show all pods: `kubectl get pods --show-all`
. Check logs: `kubectl logs -f <pod-name>` to show the output `Book{isbn=978-1-4919-1889-0, name=Minecraft Modding with Forge, cost=29.99}`
. Delete all resources: `kubectl delete -f couchbase-service.yml -f bootiful-couchbase.yml`

== Rolling Updates

All code in `rolling-update` directory:

https://github.com/arun-gupta/kubernetes-java-sample/tree/master/rolling-update

== Namespaces

. Create a new namespace: `kubectl create -f dev-namespace.yaml`
. Get namespaces: `kubectl get namespace`
. Create a new deployment in the namespace: `kubectl --namespace=development run couchbase --image=arungupta/couchbase`
. List deployments: `kubectl get deployments`
.. No deployments shown
. List all resources in the namespace: `kubectl get deployments --namespace=development`
. List all resources in all namespaces: `kubectl get deployments --all-namespaces`
. Show pods in the namespaces: `kubectl get pods --all-namespaces`

== Quota (broken)

. Create a constrained resource: `kubectl create -f quota-wildfly.yaml`
. Check for pods: `kubectl get -w pods`
. Broken: https://github.com/kubernetes/kubernetes/issues/33621

== Run-once/Batch Jobs

. Create a job: `kubectl create -f runonce-job.yaml`
. Check jobs: `kubectl get jobs`
. More details about job: `kubectl describe jobs wait`
. Check pods: `kubectl get pods`
. Show all completed pods: `kubectl get pods --show-all`

== Couchbase Cluster

https://github.com/arun-gupta/couchbase-kubernetes/tree/master/cluster

== Daemon Set (work in progress)

. Create a daemon set: `kubectl create -f prometheus-dameonset.yml`
. 

=== Tips

. Create resources in all `.json`, `.yaml` and `.yml` files in dir: `kubectl create -f ./dir`

