= Spring Boot + Couchbase + Docker + Kubernetes

== Using CLI

. Start Couchbase Docker container: `docker run -d --name db -p 8091-8094:8091-8094 -p 11210:11210 arungupta/oreilly-couchbase`
. Run the application: `mvn -f webapp/pom.xml spring-boot:run`
. Optionally
.. Generate a fat jar: `mvn -f webapp/pom.xml clean package`
.. Run app (default host): `mvn spring-boot:run` or `java -jar target/bootiful-couchbase.jar`
.. Run app (explicit host): `java -Dspring.couchbase.bootstrap-hosts=localhost -jar target/bootiful-couchbase.jar`

== Using Docker

. Start Couchbase Docker container: `docker run -d --name db -p 8091-8094:8091-8094 -p 11210:11210 arungupta/oreilly-couchbase`
. Ceate Docker image of the application: `mvn -f webapp/pom.xml clean package`
. Find IP address of the database: `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db`
. Run the application: `docker run -it -e spring.couchbase.bootstrap-hosts=<IP> arungupta/bootiful-couchbase`
. Push the image to Docker Hub: `mvn install`

== Using Kubernetes

. Start Kubernetes: `NUM_NODES=2 NODE_SIZE=m3.medium KUBERNETES_PROVIDER=aws kube-up.sh`
. Create Couchbase service: `kubectl.sh create -f couchbase-service.yml`
. Run application: `kubectl.sh create -f bootiful-couchbase.yml`

=== Expected flow (with maven plugin)

. Create Kubernetes artifacts for service + RC for `arungupta/oreilly-couchbase` - How can the name of this service be customized to be "`couchbase`"? This is used in `bootiful-couchbase.yml`.
. Create Kubernetes artifacts for `arungupta/bootiful-couchbase`
. Deploy all artifacts to Kubernetes: `mvn fabric8:deploy`

== Expected Output

. Look for output:
+
```
Book{isbn=978-1-4919-1889-0, name=Minecraft Modding with Forge, cost=29.99}
```
